### ISSUE TITLE
1.0 Checklist

### ISSUE THREAD

**Issue by wslack** [18F/federalist-guide-template#2]
Per @jz

- [ ] Documentation on how to use Jekyll for a Federal audience
- [ ] Formatted in a way that makes it easy to modify and edit
- [ ] Configurable colors and logo via config file
- [ ] Links or embeds to training videos
- [ ] Instructions about how to set it up at /help of another Federalist site

**Comment by wslack** [comment]
@line47 I am guessing this wouldn't be needed since you would fold this into your other template work?

**Comment by line47** [comment]
That's correct yeah 👍
